### ISSUE TITLE
.NET 8 scraper timing out

### ISSUE THREAD

**Issue by Coolgatty** [litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet#148]
Hello, im having trouble with my upgrade to .NET 8 in my AWS Lambda.

Everything works correctly locally, double triple checked versions and everything really, but my lambda is timing out

```
 2024-09-27T17:45:08.183Z	2f289748-79ab-4d76-adb3-a969ae42eff9	info	   at PuppeteerSharp.Helpers.TaskHelper.<>c__DisplayClass2_0.<WithTimeout>b__0() in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Helpers/TaskHelper.cs:line 48
   at PuppeteerSharp.Helpers.TaskHelper.WithTimeout(Task task, Func`1 timeoutAction, TimeSpan timeout, CancellationToken cancellationToken) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Helpers/TaskHelper.cs:line 93
   at PuppeteerSharp.FrameManager.WaitForFrameNavigationAsync(Frame frame, NavigationOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/FrameManager.cs:line 104
   at OneClick.Pagos.Interno.Scraping.Services.ScrapingService.OneClickLogin(Page page, String username, String password) in /codebuild/output/src3973464671/src/bitbucket.org/defontana/one-click/OneClick.Pagos.Interno.Scraping/Services/ScrapingService.cs:line 1150
   at OneClick.Pagos.Interno.Core.Services.OneClickService.<>c__DisplayClass7_0.<<ScrapingOneClick>b__0>d.MoveNext() in /codebuild/output/src3973464671/src/bitbucket.org/defontana/one-click/OneClick.Pagos.Interno.Core/Services/OneClickService.cs:line 75
--- End of stack trace from previous location ---
   at OneClick.Pagos.Interno.Scraping.Services.ScrapingService.ManageScrapingRetryActions(Func`3 func, Int32 maxRetry, Boolean throttled) in /codebuild/output/src3973464671/src/bitbucket.org/defontana/one-click/OneClick.Pagos.Interno.Scraping/Services/ScrapingService.cs:line 559
```

im pretty sure its because of WaitForNavigationAsync but i cant seem to trace the error.

Im not sure what else i should be providing to help identify the issue. If theres anything that i can provide let me know

![oneclick0](https://github.com/user-attachments/assets/3a8a0786-a7f0-4ef4-92bd-1eb699eb130b)
here is a picture i took with page.ScreenshotAsync(), it basically shows that nothing is loading correctly before it times out.

As it can be seen, im trying to do a login, again, works perfectly fine in local.

i read in #136 that it might be something to do with the extraction of a font? idk ive been at this for 3 days and investigating everything and nothing has worked so far.

**Comment by brianfeucht** [comment]
Hello @Coolgatty 

The font config change was causing chromium to crash.  This seems like it might be related to requests timing out in the lambda.

When you said this runs locally on you machine, in what context?  Are you using a Docker Image with the AL2023 base?  Check out https://github.com/litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet/tree/main/sample/SampleLambda-dotnet8 for an example on how to do that.

If you are using that Docker image that implies something is up either with the context the Docker image is being run in AWS or the webpage you are requesting is doing something different for network requests from your AWS account.

**Comment by Coolgatty** [comment]
Sorry, no docker just straight up net core 8 in vscode ran with dotnet watch run

Right now i updated to all the newest versions (of chromium headless and puppeteer) and im getting a different error, idk if youd be willing to check it out i made a post in Puppeteer but it might also be from this project since it happens with LaunchAsync

https://github.com/hardkoded/puppeteer-sharp/issues/2785#issuecomment-2383741597

Thanks in advance

**Comment by brianfeucht** [comment]
I'd highly recommend running in Docker locally as it is going to be much closer to the environment you will be running in Lambda. 
 AL2023 is very stripped and locked down.  I've consistently struggled to get chromium running in this environment.  Removing the `--single-process` flag is very likely going to cause you problems.  Running on a docker image locally will get you much closer to that environment.  Which means fewer surprises once deployed.
  
The other option here is stop using AL2023.  We have started building custom docker images based on Ubuntu for more advanced use cases due to the constant battles with AWS provided runtime environment.  By bringing our own run time we sidestep most of these issues.

**Comment by Coolgatty** [comment]
thanks for the response, looks like custom runtime is gonna have to be the answer.
